### ISSUE TITLE
Post Channel To River returns error message

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver-API#17]
Attempting to add a channel to a river generates an error.

Input: 
$api_client = new API_Client($api_config);
$post_headers = array(
    'Content-Type' => 'application/json',
    'Accept' => 'application/json'  
);
$request_body = json_encode(array(
   "name" => "twitter",
   "options" => array (
         "key" => "user",
         "value" => "crowdmap"
   )
));
$response = $api_client->exec_api_request('/rivers/1/channel', $request_body, "POST", $post_headers);
echo json_encode($response);

Response:
Fatal error: Uncaught exception 'Exception' with message 'An error occurred: '

Attempting to create an RSS channel returns the same error:
$request_body = json_encode(array(
   "name" => "rss",
   "options" => array (
         "key" => "url",
         "title" => "PNWER Test Points",
         "value" => "http://incident.co.pierce.wa.us/firsttosee/feeds/SocialMediaDataPoints.rss"
   )
));

**Comment by ekala** [comment]
The resource for creating channels is `rivers/:river_id/channels`. However, you're sending the request to `rivers/:river_id/channel`

**Comment by ekala** [comment]
Closing.
