### ISSUE TITLE
The API does not return a value for a tweet's original URL

### ISSUE THREAD

**Issue by dan-king** [ushahidi/SwiftRiver-API#49]
The API returns blank values for tweets original URL

The attached example shows a tweet from user @Chapter5band. The orginal_url of the tweet is 
https://twitter.com/Chapter5band/status/351777499279142916 but shows up blank in the response from the API

![swiftriver api - drop details - blank original_url](https://f.cloud.github.com/assets/2077370/732691/b2a84ffa-e289-11e2-9ca0-e8badb38436a.png)

**Comment by dan-king** [comment]
Note: The search request can be used to construct the original URL using the $source['username'] and $original_id values.

https://wiki.ushahidi.com/display/WIKI/SwiftRiver+API+Search+Resources#SwiftRiverAPISearchResources-GETsearch/drops

i.e.
$original_tweet_url =   "https://twitter.com/" . $source['username']. "/status/" . $original_id;

**Comment by ekala** [comment]
@dan-king I fixed this in the app the Twitter streaming app.

Closing

**Comment by dan-king** [comment]
Thanks Emmanuel. Do I have to install an update to get the fix? (Sorry, I'm
still a noobJ)

-----Original Message-----
