### ISSUE TITLE
/drops/search endpoint

### ISSUE THREAD

**Issue by ekala** [ushahidi/SwiftRiver-API#7]
Add a search endpoint to the drops controller. The endpoint will only accept HTTP GET requests and the following parameters:
- channels - Comma separated list of channels e.g. `rss,sms,twitter`
- keywords 
- location - bounding box

**Comment by 69mb** [comment]
No verbs in resource urls. Should be GET /drops instead.

**Comment by ekala** [comment]
Right. So allow both GET and POST on /drops or use a totally separate controller for search?

**Comment by brianherbert** [comment]
Not sure if this is helpful but from the Crowdmap side, we just use filters as GET params for searching. So, to get all posts, GET /posts/ and to search GET/posts/?q=some%20keywords (and other filters for date ranges, map bounds, etc).

**Comment by ekala** [comment]
For purposes of search, I don't think resource URIs are practical. As such, I'm leaning towards having a collection of endpoints for searching the various resources (drops, buckets, rivers and accounts)

```
search/drops
search/buckets
search/rivers
search/accounts
```

The standard query parameters for each of these endpoints would be:
- q - **required** UTF-8 URL encoded search query
- page - _optional_ Page number to fetch. Default is `1`.
- count - _optional_  No. of objects to return per page. Default is `50`

Thoughts?
